### PR TITLE
Functions now in GA, swap exp. SDK with standard

### PR DESCRIPTION
**Pull request by haakonvt**

### CODE REVIEW

**Comment by haakonvt** [comment]
@HMEiding @qTipTip any particular version that works/doesn't work atm? (I just went with the newest)

**Review by ks93 — APPROVED** [review]
Looks great!

**Comment by haakonvt** [comment]
> Looks great!

```
from cognite.experimental import CogniteClient
ModuleNotFoundError: No module named 'cognite.experimental'
```
# 😅

**Comment by ks93** [comment]
> > Looks great!
> 
> ```
> from cognite.experimental import CogniteClient
> ModuleNotFoundError: No module named 'cognite.experimental'
> ```
> # 😅 

I take it back 😅

**Review by HMEiding — CHANGES_REQUESTED** [review]
Great! 😃 However, we don't yet support major version 4 of the main SDK yet. We first have to get [this PR](https://github.com/cognitedata/context-api-workers/pull/1939) through. Requesting changes so we don't accidentally merge before that.

**Comment by haakonvt** [comment]
> Great! 😃 However, we don't yet support major version 4 of the main SDK yet. We first have to get [this PR](https://github.com/cognitedata/context-api-workers/pull/1939) through. Requesting changes so we don't accidentally merge before that.

I see! But that doesn't matter for this PR, as this is the action, not the template. Which reminds me to update the template as well 😅

**Pull request merged**
